import streamlit as st
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

## All dependencies are now loaded and you can start coding

st.title("LAWS90286")

# 1. Ask user for their name
st.header("Question One")
st.session_state.name = st.text_input("What's your name?")

# Store import variables in a session_state

# 2. If the user enters their name and licks a button, displays a welcome message to the user.
if "name" not in st.session_state:
    st.session_state.name = ""

if "button_value" not in st.session_state:
    st.session_state.button_value = False

st.header("Question Two")
st.session_state.button_value = st.button("Click here!")

if st.session_state.name != "" and st.session_state.button_value == True:
    st.write(f"Hello, {st.session_state.name}!")


# 3. The welcome message should be generated by GPT-4o
    st.header("Question Three")
    client = OpenAI()

    response = client.response.create(
        model="gpt-4o",
        input=f"Greet {st.session_state.name}",
    )

    st.write(response.output_text)



# 4. 
